name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      product-db:
        image: postgres:latest
        ports:
          - 5435:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: productdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      order-db:
        image: postgres:latest
        ports:
          - 5434:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: orderdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Test product-service
      - name: Run Product Service Tests
        run: |
          docker-compose up -d product-db
          docker-compose run product-service-test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5435
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: productdb

      # Test order-service
      - name: Run Order Service Tests
        run: |
          docker-compose up -d order-db
          docker-compose run order-service-test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5434
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: orderdb

      # Build Docker images if tests pass
      - name: Build Product Service Image
        if: success()
        run: |
          docker-compose build product-service

      - name: Build Order Service Image
        if: success()
        run: |
          docker-compose build order-service

      - name: Build API Gateway Image
        if: success()
        run: |
          docker-compose build api-gateway
